; stop.g
; called when M0 (Stop) is run (e.g. when a print from SD card is cancelled)
;
; generated by RepRapFirmware Configuration Tool v3.4.0-LPC-STM32+4 on Mon Nov 21 2022 17:18:54 GMT+0300 (Москва, стандартное время)

